/** Freeze component decisions on temporal validation before evaluating any holdout. */
import fs from 'node:fs';import zlib from 'node:zlib';import {buildModel,scoringEnvironment,exactProbabilities} from '../../js/nhl/model.js';import {probabilityMetrics} from '../../js/shared/statistics.js';
fs.mkdirSync('/tmp/nhl-final-audit',{recursive:true});
const root=new URL('../../',import.meta.url),history=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('data/nhl/history.json.gz',root)))),original=JSON.parse(fs.readFileSync(new URL('data/nhl/audit-protocol.json',root))).originalConfig;
const candidates=[{...original,goalieRecentWeight:.3,finishingWeight:1},{...original,goalieRecentWeight:0,finishingWeight:1},{...original,goalieRecentWeight:.3,finishingWeight:0},{...original,goalieRecentWeight:0,finishingWeight:0}];
const byTeam=Object.fromEntries(Object.keys(history.teams).map(t=>[t,history.games.filter(g=>g.home===t||g.away===t)]));
const logit=p=>Math.log(p/(1-p)),sigmoid=x=>1/(1+Math.exp(-x));
function evaluate(season,configs){const rows=configs.map(()=>[]),targets=history.games.filter(g=>g.season===season);let models,date;for(const [index,g] of targets.entries()){const cutoff=g.date+'T00:00:00Z';if(date!==g.date){models=configs.map(config=>buildModel(history,{asOf:cutoff,season,config}));date=g.date;}const rest=t=>{const prior=byTeam[t].filter(x=>x.date<g.date).at(-1);return prior?(Date.parse(g.date)-Date.parse(prior.date))/86400000:null;};for(let i=0;i<configs.length;i++){const e=scoringEnvironment(models[i],g.home,g.away,{homeA:!g.neutral,restA:rest(g.home),restB:rest(g.away)}),p=exactProbabilities(e,configs[i]);rows[i].push({gameId:g.id,date:g.date,p:p.fullGameA,y:g.homeScore>g.awayScore?1:0,regulationA:p.regulationA,regulationB:p.regulationB,overtime:p.overtime,actualOvertime:g.ending==='REG'?0:1,expectedA:e.a,expectedB:e.b});}if(index%400===0)console.log(`Followup ${season}: ${index}/${targets.length}`);}return rows;}
const validation=evaluate(2024,candidates),split=Math.floor(validation[0].length*2/3),comparison=candidates.map((config,i)=>({config,early:probabilityMetrics(validation[i].slice(0,split)),late:probabilityMetrics(validation[i].slice(split)),all:probabilityMetrics(validation[i])}));
const selectedIndex=comparison.reduce((best,c,i)=>c.early.logLoss<comparison[best].early.logLoss?i:best,0),check=comparison[selectedIndex].late,reference=comparison[0].late;
const adopt=selectedIndex!==0&&check.logLoss<reference.logLoss-.001&&check.brier<reference.brier-.0005,index=adopt?selectedIndex:0,selectedConfig=candidates[index];
// Symmetric temperature calibration preserves arbitrary neutral-matchup exchange symmetry.
const early=validation[index].slice(0,split),late=validation[index].slice(split),calibrate=(rs,slope)=>rs.map(r=>({...r,p:sigmoid(logit(r.p)*slope)}));let slope=1,best=probabilityMetrics(early).logLoss;for(let s=.4;s<=1.4001;s+=.025){const loss=probabilityMetrics(calibrate(early,s)).logLoss;if(loss<best){best=loss;slope=Number(s.toFixed(3));}}
const lateCalibrated=probabilityMetrics(calibrate(late,slope)),lateRaw=probabilityMetrics(late),temperatureAdopt=lateCalibrated.logLoss<lateRaw.logLoss-.001&&lateCalibrated.brier<lateRaw.brier-.0005;
if(temperatureAdopt)throw Error('Calibration validated: serving-model implementation and coherent outcome mapping required before proceeding.');
const decision={selectedConfig,adopt,selectedIndex,componentSelection:'Lowest early-validation log loss among four predeclared variants; require late-validation improvement >0.001 log loss AND >0.0005 Brier.',calibration:{method:'Symmetric logit temperature, intercept fixed zero to preserve neutral-team exchange symmetry',slope,lateRaw,lateCalibrated,adopt:temperatureAdopt},frozenAt:new Date().toISOString()};
fs.writeFileSync('/tmp/nhl-final-audit/frozen-decision.json',JSON.stringify(decision,null,2));console.log('DECISION FROZEN',JSON.stringify(decision));
// Only after decision is written do we calculate previously reported holdout and reserved small current-season sample.
const holdout=evaluate(2025,[candidates[0],selectedConfig]),reserved=evaluate(2026,[candidates[0],selectedConfig]);
const report={protocol:'Original 2025 holdout previously seen, not pristine; model decisions restricted to 2024 temporal validation. 2026 outcomes not evaluated until this frozen decision; only 43 games, not an adequate season.',decision,validation:comparison,holdout:holdout.map(rs=>probabilityMetrics(rs)),reserved2026:reserved.map(rs=>probabilityMetrics(rs)),validationPredictions:validation[index],holdoutPredictions:holdout[index===0?0:1],reservedPredictions:reserved[index===0?0:1]};
fs.writeFileSync('/tmp/nhl-final-audit/followup.json',JSON.stringify(report)+'\n');console.log(JSON.stringify({selectedConfig,holdout:report.holdout.map(({calibration,...r})=>r),reserved:report.reserved2026.map(({calibration,...r})=>r)},null,2));
