import fs from 'node:fs';import zlib from 'node:zlib';import {probabilityMetrics,clamp} from '../../js/shared/statistics.js';import {buildModel,scoringEnvironment,exactProbabilities} from '../../js/nhl/model.js';
fs.mkdirSync('/tmp/nhl-final-audit',{recursive:true});
const root=new URL('../../',import.meta.url),h=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('data/nhl/history.json.gz',root)))),original=JSON.parse(fs.readFileSync(new URL('data/nhl/audit-protocol.json',root))).originalConfig;
const methods=['season','last20','last10','last5','blended','exponentialGames','exponentialDays'];const byTeam=Object.fromEntries(Object.keys(h.teams).map(t=>[t,h.games.filter(g=>g.home===t||g.away===t)]));
function share(rs,t,method,cutoff){function window(n,w){const rows=n?rs.slice(-n):rs;let gf=0,ga=0;for(const [i,g] of rows.entries()){const weight=w?w(g,i,rows.length):1;gf+=g.sides[t]['5on5'].xgf*weight;ga+=g.sides[t]['5on5'].xga*weight;}return gf+ga?gf/(gf+ga):.5;}
 const s=window();let recent=s,n=rs.length;if(method.startsWith('last')){n=Math.min(n,Number(method.slice(4)));recent=window(Number(method.slice(4)));}if(method==='blended')recent=.4*window(20)+.3*window(10)+.15*window(5)+.15*s;if(method==='exponentialGames')recent=window(null,(g,i,n)=>.5**((n-1-i)/10));if(method==='exponentialDays')recent=window(null,g=>.5**((Date.parse(cutoff)-Date.parse(g.date))/86400000/30));return(recent*n+s*10)/(n+10);}
const predictions={},sos={};for(const season of [2024,2025,2026]){const rows=Object.fromEntries(methods.map(m=>[m,[]]));let date,base,models;for(const [index,g] of h.games.filter(g=>g.season===season).entries()){const cutoff=g.date+'T00:00:00Z',eligible=t=>byTeam[t].filter(x=>x.season===season&&x.availableAt<cutoff);for(const method of methods)rows[method].push({gameId:g.id,p:clamp(.5+.8*(share(eligible(g.home),g.home,method,cutoff)-share(eligible(g.away),g.away,method,cutoff)),.05,.95),y:g.homeScore>g.awayScore?1:0});
 if(season===2024){if(date!==g.date){base=buildModel(h,{season,asOf:cutoff,config:original});models=[.5,1].map(alpha=>{const teams={};for(const [t,team] of Object.entries(base.teams)){const rs=eligible(t),opponents=rs.map(x=>base.teams[x.home===t?x.away:x.home].features['5on5']);const average=k=>opponents.length?opponents.reduce((s,o)=>s+o[k],0)/opponents.length:base.league['5on5'][k];const attackAdjustment=clamp(base.league['5on5'].adjustedXga60/average('adjustedXga60'),.75,1.25)**alpha,defenseAdjustment=clamp(base.league['5on5'].adjustedXgf60/average('adjustedXgf60'),.75,1.25)**alpha;teams[t]={...team,features:{...team.features,'5on5':{...team.features['5on5'],adjustedXgf60:team.features['5on5'].adjustedXgf60*attackAdjustment,adjustedXga60:team.features['5on5'].adjustedXga60*defenseAdjustment}}};}return{...base,teams};});date=g.date;}
 const rest=t=>{const previous=byTeam[t].filter(x=>x.date<g.date).at(-1);return previous?(Date.parse(g.date)-Date.parse(previous.date))/86400000:null;};for(const [i,model] of [base,...models].entries()){const e=scoringEnvironment(model,g.home,g.away,{homeA:!g.neutral,restA:rest(g.home),restB:rest(g.away)});(sos[i]??=[]).push({p:exactProbabilities(e,original).fullGameA,y:g.homeScore>g.awayScore?1:0});}}
 if(index%500===0)console.log(`Baselines ${season}: ${index}`);
 }predictions[season]=rows;}
const metrics=Object.fromEntries(Object.entries(predictions).map(([s,methods])=>[s,Object.fromEntries(Object.entries(methods).map(([m,rs])=>[m,probabilityMetrics(rs)]))]));const selected=Object.entries(metrics[2024]).sort((a,b)=>a[1].logLoss-b[1].logLoss)[0][0];
fs.writeFileSync('/tmp/nhl-final-audit/baselines.json',JSON.stringify({selection:'Lowest 2024 validation log loss only; no holdout selection',selected,metrics,selectedPredictions:predictions[2025][selected],sosValidation:Object.entries(sos).map(([index,rs])=>({alpha:[0,.5,1][index],...probabilityMetrics(rs)}))})+'\n');console.log(JSON.stringify({selected,sos:Object.entries(sos).map(([index,rs])=>({alpha:[0,.5,1][index],...probabilityMetrics(rs)}))},null,2));
