import fs from 'node:fs';import {simulate,scoringEnvironment,exactProbabilities,buildModel} from '../../js/nhl/model.js';import {goalSample,randomSeed} from '../../js/shared/statistics.js';import zlib from 'node:zlib';
fs.mkdirSync('/tmp/nhl-final-audit',{recursive:true});
const root=new URL('../../',import.meta.url),snapshot=JSON.parse(fs.readFileSync(new URL('data/nhl/snapshot.json',root))),history=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('data/nhl/history.json.gz',root))));
const model=snapshot.model,codes=Object.keys(model.teams);let min=Infinity,max=0,maxMCError=0;const convergence=[];
for(const distribution of ['poisson','negative-binomial'])for(const [a,b] of [['CAR','NYR'],['TOR','BOS'],['UTA','VGK']]){const m={...model,config:{...model.config,distribution}},e=scoringEnvironment(m,a,b,{homeA:true}),exact=exactProbabilities(e,m.config);let means=0,variance=0,ot=0;const ps=[];
 for(let seed=1;seed<=100;seed++){const r=simulate(m,a,b,{homeA:true},{random:randomSeed(seed)});const p=r.monteCarlo?.fullGameA??r.fullGameA;ps.push(p);means+=p;ot+=r.monteCarlo?.overtime??r.overtime;maxMCError=Math.max(maxMCError,Math.abs(p-exact.fullGameA));if(Math.abs(r.regulationA+r.regulationB+r.overtime-1)>1e-9)throw Error('Incoherent probabilities');}means/=100;ot/=100;variance=ps.reduce((s,p)=>s+(p-means)**2,0)/99;convergence.push({distribution,a,b,exact:exact.fullGameA,mcMean:means,mcSD:Math.sqrt(variance),expectedSD:Math.sqrt(exact.fullGameA*(1-exact.fullGameA)/10000),meanOT:ot,analyticalOT:exact.overtime});}
for(const a of codes)for(const b of codes)if(a!==b){const e=scoringEnvironment(model,a,b,{homeA:true});min=Math.min(min,e.a,e.b);max=Math.max(max,e.a,e.b);}
const samples={};for(const distribution of ['poisson','negative-binomial']){let s=0,s2=0;const random=randomSeed(42);for(let i=0;i<200000;i++){const x=goalSample(3,distribution,20,random);s+=x;s2+=x*x;}samples[distribution]={mean:s/200000,variance:s2/200000-(s/200000)**2,expectedMean:3,expectedVariance:distribution==='poisson'?3:3+9/20};}
// Deterministic historical traces across both evaluation years; verify exact eligible ID sets.
const traces=[];for(const year of [2024,2025]){const targets=history.games.filter(g=>g.season===year);const pick=randomSeed(year+73);for(let trace=0;trace<5;trace++){const g=targets[Math.floor(targets.length*pick())],cutoff=g.date+'T00:00:00Z',m=buildModel(history,{season:year,asOf:cutoff,config:model.config}),teamTraces=[];for(const t of [g.home,g.away]){const eligible=history.games.filter(x=>x.season===year&&x.availableAt<cutoff&&(x.home===t||x.away===t));const goalies=history.goalieGames.filter(r=>r.availableAt<cutoff);if(m.teams[t].windows.season.games!==eligible.length)throw Error('Window count mismatch');if(eligible.some(x=>x.id===g.id||x.date>=g.date)||goalies.some(x=>x.gameId===g.id||x.date>=g.date))throw Error('Leakage');teamTraces.push({team:t,currentGames:eligible.length,last10Ids:eligible.slice(-10).map(x=>x.id),latestTeamDate:eligible.at(-1)?.date,starterStatus:m.teams[t].goalie.status,candidateIds:m.teams[t].goalie.candidates.map(x=>x.id),latestEligibleGoalieDate:goalies.map(r=>r.date).sort().at(-1)});}traces.push({gameId:g.id,date:g.date,cutoff,teams:teamTraces});}}
const report={minExpectedGoals:min,maxExpectedGoals:max,maxSingleTrialProbabilityError:maxMCError,convergence,distributionSamples:samples,historicalTraces:traces};fs.writeFileSync('/tmp/nhl-final-audit/simulation.json',JSON.stringify(report,null,2));console.log(JSON.stringify({minExpectedGoals:min,maxExpectedGoals:max,maxSingleTrialProbabilityError:maxMCError,distributionSamples:samples},null,2));
