/** One-shot frozen draw-model holdout evaluation. Refuses accidental repeated tuning passes. */
import fs from 'node:fs';import {features} from './draw_features.js';import {regulationDistribution,outcomeProbabilities} from '../../js/nhl/regulation.js';import {probabilityMetrics} from '../../js/shared/statistics.js';
const root=new URL('../../',import.meta.url),decision=JSON.parse(fs.readFileSync(new URL('data/nhl/draw-decision.json',root))),out=new URL('data/nhl/draw-holdout.json',root),marker=new URL('data/nhl/.draw-holdout-evaluated',root);
if(fs.existsSync(out)||fs.existsSync(marker))throw Error('Frozen holdout already evaluated. Read draw-holdout.json; no second tuning/evaluation pass.');
fs.writeFileSync(marker,decision.frozenAt,{flag:'wx'});
const rows=features([2025]);
function evaluate(spec){const predictions=[];let scoreLoss=0;for(const r of rows){const config={...decision.frozenTeamStrength,regulation:spec,overtimeMode:decision.overtimeMode},d=regulationDistribution(r,config),p=outcomeProbabilities(r,config,d);predictions.push({...r,p:p.fullGameA,overtime:p.overtime,regulationA:p.regulationA,regulationB:p.regulationB,conditionalOT:p.overtimeConditionalA,meanA:d.meanA,meanB:d.meanB});scoreLoss-=Math.log(Math.max(1e-15,d.matrix[r.regHome*d.size+r.regAway]));}return{winner:probabilityMetrics(predictions),draw:probabilityMetrics(predictions.map(r=>({p:r.overtime,y:r.draw}))),predictedTieRate:predictions.reduce((s,r)=>s+r.overtime,0)/rows.length,observedTieRate:rows.filter(r=>r.draw).length/rows.length,regulationScoreLogLoss:scoreLoss/rows.length,predictions};}
const selected=evaluate(decision.regulation),previous=evaluate({family:'poisson'});delete previous.predictions;
const report={decisionFrozenAt:decision.frozenAt,evaluatedAt:new Date().toISOString(),policy:'One evaluation after frozen training/validation decision; no post-holdout tuning. Existing season was previously reported, not pristine.',selected,previous};
fs.writeFileSync(out,JSON.stringify(report)+'\n');fs.unlinkSync(marker);console.log(JSON.stringify({selected:{predictedTieRate:selected.predictedTieRate,observedTieRate:selected.observedTieRate,winner:selected.winner,draw:selected.draw},previous:{predictedTieRate:previous.predictedTieRate,winner:previous.winner}},null,2));
