/** Diagnostic summaries use training/validation only; holdout metrics are read from its frozen one-shot artifact. */
import fs from 'node:fs';import zlib from 'node:zlib';import {regulationDistribution,outcomeProbabilities} from '../../js/nhl/regulation.js';
const root=new URL('../../',import.meta.url),selection=JSON.parse(fs.readFileSync('/tmp/nhl-draw-v11/selection.json')),data=JSON.parse(fs.readFileSync('/tmp/nhl-draw-v11/training-validation-features.json')),holdout=JSON.parse(fs.readFileSync(new URL('data/nhl/draw-holdout.json',root))),sim=JSON.parse(fs.readFileSync(new URL('data/nhl/draw-simulation.json',root))),history=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('data/nhl/history.json.gz',root))));
const mean=xs=>xs.reduce((a,b)=>a+b,0)/xs.length;
function moments(rows,a=r=>r.regHome,b=r=>r.regAway){const A=rows.map(a),B=rows.map(b),ma=mean(A),mb=mean(B),va=A.reduce((s,x)=>s+(x-ma)**2,0)/(rows.length-1),vb=B.reduce((s,x)=>s+(x-mb)**2,0)/(rows.length-1),cov=A.reduce((s,x,i)=>s+(x-ma)*(B[i]-mb),0)/(rows.length-1);return{games:rows.length,meanA:ma,meanB:mb,varianceA:va,varianceB:vb,covariance:cov,correlation:va*vb>0?cov/Math.sqrt(va*vb):null};}
function group(rows,pick,edges){return edges.slice(0,-1).map((lo,i)=>{const hi=edges[i+1],rs=rows.filter(r=>pick(r)>=lo&&pick(r)<hi);return{lower:lo,upper:Number.isFinite(hi)?hi:null,games:rs.length,predictedTieRate:rs.length?mean(rs.map(r=>r.predictedDraw)):null,observedTieRate:rs.length?mean(rs.map(r=>r.draw)):null,correlation:rs.length>1?moments(rs).correlation:null};});}
function auc(rows,pick){const positive=rows.filter(r=>r.draw),negative=rows.filter(r=>!r.draw);let score=0;for(const a of positive)for(const b of negative){const diff=pick(a)-pick(b);score+=diff>0?1:diff===0?.5:0;}return score/(positive.length*negative.length);}
const diagnosis={};
for(const year of [2023,2024]){const rows=data.filter(r=>r.season===year).map(r=>({...r,predictedDraw:regulationDistribution(r,{regulation:selection.frozen.regulation}).overtime,previousDraw:regulationDistribution(r,{regulation:{family:'poisson'}}).overtime}));const goalGames=history.games.filter(g=>g.season===year);let equal=0,neutral=0,previous=0;const diagonal=[];
 for(const r of rows){previous+=r.previousDraw;equal+=regulationDistribution({a:(r.a+r.b)/2,b:(r.a+r.b)/2},{regulation:{family:'poisson'}}).overtime;neutral+=regulationDistribution({a:r.neutral?r.a:r.a/selection.frozen.frozenTeamStrength.homeFactor,b:r.neutral?r.b:r.b*selection.frozen.frozenTeamStrength.homeFactor},{regulation:{family:'poisson'}}).overtime;}
 for(let k=0;k<=5;k++){const actual=rows.filter(r=>r.regHome===k&&r.regAway===k).length/rows.length;let before=0,after=0;for(const r of rows){const d=regulationDistribution(r,{regulation:{family:'poisson'}}),q=regulationDistribution(r,{regulation:selection.frozen.regulation});before+=d.matrix[k*d.size+k];after+=q.matrix[k*q.size+k];}diagonal.push({score:`${k}-${k}`,actualRate:actual,previousRate:before/rows.length,selectedRate:after/rows.length});}
 diagnosis[year]={moments:moments(rows),residualMoments:moments(rows,r=>r.regHome-r.a,r=>r.regAway-r.b),predictedInputTotal:mean(rows.map(r=>r.a+r.b)),observedRegulationTotal:mean(rows.map(r=>r.regHome+r.regAway)),previousTieRate:previous/rows.length,equalizedRateDiagnostic:equal/rows.length,neutralHomeDiagnostic:neutral/rows.length,drawAUC:{previous:auc(rows,r=>r.previousDraw),selected:auc(rows,r=>r.predictedDraw)},byDifferential:group(rows,r=>Math.abs(r.a-r.b),[0,.25,.5,1,Infinity]),byTotal:group(rows,r=>r.a+r.b,[0,5.5,6,6.5,7,Infinity]),byFavorite:group(rows,r=>r.favorite,[.5,.55,.6,.65,.7,1.00001]),byActualShotsExploratory:group(rows,r=>r.actualShots,[0,45,55,65,Infinity]),byActualXgExploratory:group(rows,r=>r.actualTotalXg,[0,5,6,7,Infinity]),byVenue:{homeFavored:rows.filter(r=>r.a>=r.b&&!r.neutral).length,awayFavored:rows.filter(r=>r.a<r.b&&!r.neutral).length,neutral:rows.filter(r=>r.neutral).length},diagonal,extraTimeIncludedInHistoricalAllSituation:goalGames.filter(g=>g.sides[g.home].all.seconds>3600).length};
 for(const key of ['homeFavored','awayFavored','neutral']){const rs=rows.filter(r=>key==='neutral'?r.neutral:!r.neutral&&(key==='homeFavored'?r.a>=r.b:r.a<r.b));diagnosis[year].byVenue[key]={games:rs.length,predictedTieRate:rs.length?mean(rs.map(r=>r.predictedDraw)):null,observedTieRate:rs.length?mean(rs.map(r=>r.draw)):null};}
}
const report={modelVersion:selection.frozen.modelVersion,decision:selection.frozen,candidates:selection.candidates,trainingParameterFits:selection.fits,diagnosis,holdout:{selected:Object.fromEntries(Object.entries(holdout.selected).filter(([key])=>key!=='predictions')),previous:holdout.previous,evaluatedAt:holdout.evaluatedAt,decisionFrozenAt:holdout.decisionFrozenAt},simulation:sim,limitations:['Residual holdout tie underprediction of 3.8 percentage points; no holdout tuning.','Constant odds calibration improves probability quality but preserves previous game ranking/AUC.','Retrospective MoneyPuck revisions and assumed next-day-noon availability remain.','Historical all-situation exposure includes extra time; frozen strength inputs retain this limitation.','Shared scoring/correlation diagnostics are descriptive; actual-game shot/xG bins are never pregame features.']};
fs.writeFileSync(new URL('data/nhl/draw-summary.json',root),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(diagnosis,null,2));
