/** Serving-model distribution sanity and Monte Carlo convergence; never evaluates historical holdout. */
import fs from 'node:fs';import {simulate,scoringEnvironment} from '../../js/nhl/model.js';import {regulationDistribution,outcomeProbabilities,scoreSampler} from '../../js/nhl/regulation.js';import {randomSeed} from '../../js/shared/statistics.js';
const root=new URL('../../',import.meta.url),snapshot=JSON.parse(fs.readFileSync(new URL('data/nhl/snapshot.json',root))),model=snapshot.model,codes=Object.keys(model.teams);
const pairs=[];for(const a of codes)for(const b of codes)if(a!==b){const expected=scoringEnvironment(model,a,b,{homeA:true}),d=regulationDistribution(expected,model.config),p=outcomeProbabilities(expected,model.config,d);pairs.push({a,b,expected,d,p});if(Math.abs(p.regulationA+p.regulationB+p.overtime-1)>1e-10||p.fullGameA<p.regulationA-1e-10||p.fullGameB<p.regulationB-1e-10||d.omittedTail>1e-9)throw Error('Invalid score probabilities');}
const take=f=>[...pairs].sort(f)[0];const even=take((a,b)=>Math.abs(a.expected.a-a.expected.b)-Math.abs(b.expected.a-b.expected.b)),favorite=take((a,b)=>b.p.fullGameA-a.p.fullGameA),high=take((a,b)=>b.expected.a+b.expected.b-a.expected.a-a.expected.b),low=take((a,b)=>a.expected.a+a.expected.b-b.expected.a-b.expected.b);
const candidates=model.teams.NYR.goalie.candidates;const sorted=[...candidates].sort((a,b)=>b.regressedGsax60-a.regressedGsax60);
const scenarios=[{name:'even',a:even.a,b:even.b,context:{homeA:true}},{name:'favorite',a:favorite.a,b:favorite.b,context:{homeA:true}},{name:'high-total',a:high.a,b:high.b,context:{homeA:true}},{name:'low-total',a:low.a,b:low.b,context:{homeA:true}}];
for(const [name,g] of [['strong-goalie',sorted[0]],['weak-goalie',sorted.at(-1)]])if(g)scenarios.push({name,a:'CAR',b:'NYR',context:{homeA:true,goalieB:{id:g.id,status:'projected',source:'Hypothetical validation scenario from past observations',observedAt:model.teams.NYR.goalie.sourceTimestamp}}});
const results=[];for(const [index,s] of scenarios.entries()){
 const e=scoringEnvironment(model,s.a,s.b,s.context),d=regulationDistribution(e,model.config),p=outcomeProbabilities(e,model.config,d),diagonal=Array.from({length:5},(_,k)=>({score:`${k}-${k}`,probability:d.matrix[k*d.size+k]})),convergence=[];
 for(const trials of [10000,100000,1000000]){const result=simulate(model,s.a,s.b,s.context,{trials,random:randomSeed(113+index+trials)}),mc=result.monteCarlo,errors={};for(const [key,value] of [['fullGameA',p.fullGameA],['overtime',p.overtime],['regulationA',p.regulationA]]){const se=Math.sqrt(value*(1-value)/trials);errors[key]={analytical:value,sampled:mc[key],error:mc[key]-value,standardError:se,z:se?(mc[key]-value)/se:0};if(Math.abs(mc[key]-value)>6*se+1/trials)throw Error('Monte Carlo did not converge');}convergence.push({trials,errors,sampledFinalMeanA:mc.averageA,analyticalFinalMeanA:result.averageA,sampledFinalMeanB:mc.averageB,analyticalFinalMeanB:result.averageB});}
 const sample=scoreSampler(d),random=randomSeed(997+index),counts=Array(5).fill(0);let sa=0,sb=0,saa=0,sbb=0,cross=0;for(let n=0;n<1000000;n++){const [a,b]=sample(random);sa+=a;sb+=b;saa+=a*a;sbb+=b*b;cross+=a*b;if(a===b&&a<5)counts[a]++;}
 results.push({name:s.name,a:s.a,b:s.b,scenario:s.context,goalRateInputs:{a:e.a,b:e.b},regulationMeans:{a:d.meanA,b:d.meanB},variances:{a:d.varianceA,b:d.varianceB},covariance:d.covariance,omittedTail:d.omittedTail,probabilities:p,diagonal,highScoreTail:d.matrix.reduce((sum,p,n)=>sum+(Math.floor(n/d.size)>=10||n%d.size>=10?p:0),0),convergence,regulationSample:{trials:1000000,meanA:sa/1e6,meanB:sb/1e6,varianceA:saa/1e6-(sa/1e6)**2,varianceB:sbb/1e6-(sb/1e6)**2,covariance:cross/1e6-sa*sb/1e12,diagonal:counts.map((n,k)=>({score:`${k}-${k}`,sampled:n/1e6,analytical:diagonal[k].probability}))}});
 console.log(`Verified ${s.name}: ${s.a}/${s.b}`);
}
fs.writeFileSync(new URL('data/nhl/draw-simulation.json',root),JSON.stringify({modelVersion:snapshot.metadata.modelVersion,directedMatchupsChecked:pairs.length,scenarios:results},null,2)+'\n');
